"""add relationship between user and item

Revision ID: 926a078fda3e
Revises: 1d6083ab9bcf
Create Date: 2026-07-08 14:55:37.595437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926a078fda3e'
down_revision: Union[str, Sequence[str], None] = '1d6083ab9bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
